const SectionList = [
    {
        id: 1,
        divID: 'white',
        txtContainer: 'white-txt-container',
        titleClass: '',
        titleTxt: '',
        headlineClass: 'white-headline',
        headlineTxt: 'We deliver results',
        paragraphClass: 'white-paragraph',
        paragraphTxt: 'Whether we’re building a new product or improving an existing one, FIVE partners with our clients to make a measurable impact. We’ve helped hundreds of organizations, including large enterprises, small businesses and even non-profits.',
        buttonClass: 'white-button',
        buttonTxt: 'Learn more about us',
        imgContainer: '',
        img: '',
        imgURL: '',
        imgBgContainer: '',
        imgBg: ''
    },
    {
        id: 2,
        divID: 'yellow',
        txtContainer: 'yellow-txt-container',
        titleClass: 'yellow-title',
        titleTxt: 'ROSETTA STONE',
        headlineClass: 'yellow-headline',
        headlineTxt: '5.8x Revenue Increase',
        paragraphClass: 'yellow-paragraph',
        paragraphTxt: "5.8x increased revenue for the world's premiere language-learning app.",
        buttonClass: '',
        buttonTxt: '',
        imgContainer: 'yellow-image-container',
        imgDiv: 'yellow-img-div',
        img: 'yellow-image',
        imgURL: 'https://mk0fivefiveagen2f17j.kinstacdn.com/wp-content/uploads/2020/04/rosetta-case-mobile-384x780.png',
        imgBgContainer: 'yellow-img-bg-container',
        imgBg: 'yellow-img-bg'
    },
    {
        id: 3,
        divID: 'purple',
        txtContainer: 'purple-txt-container',
        titleClass: 'purple-title',
        titleTxt: 'MARRIOTT',
        headlineClass: 'purple-headline',
        headlineTxt: '62% Returning Users',
        paragraphClass: 'purple-paragraph',
        paragraphTxt: "More than 60% of Marriott's users return to the hotel industry's first virtual assistant, averaging 4-minute sessions with 50 exchanged messages",
        buttonClass: '',
        buttonTxt: '',
        imgContainer: 'purple-image-container',
        img: 'purple-image',
        imgURL: "https://mk0fivefiveagen2f17j.kinstacdn.com/wp-content/uploads/2020/04/marriott-case-mobile-384x780.png",
        imgBg: 'purple-img-bg'
    },
    {
        id: 4,
        divID: 'red',
        txtContainer: 'red-txt-container',
        titleClass: 'red-title',
        titleTxt: 'SUPERMAJORITY',
        headlineClass: 'red-headline',
        headlineTxt: 'The Power of Women',
        paragraphClass: 'red-paragraph',
        paragraphTxt: "We are helping SuperMajority build tools used to create the largest women-to-women voter engagement program in 2020.",
        buttonClass: 'red-button',
        buttonTxt: 'CASE STUDY COMING SOON',
        imgContainer: 'red-image-container',
        img: 'red-image',
        imgURL: "https://mk0fivefiveagen2f17j.kinstacdn.com/wp-content/uploads/2020/10/supermajority-case-desktop-1137x695.png",
        imgBg: 'red-img-bg'
    },
    {
        id: 5,
        divID: 'brown',
        txtContainer: 'brown-txt-container',
        titleClass: 'brown-title',
        titleTxt: 'STARZ',
        headlineClass: 'brown-headline',
        headlineTxt: '228% Push Opt-in Increase',
        paragraphClass: 'brown-paragraph',
        paragraphTxt: "We are partnering with Starz to increase engagement in the form of strategic and operational support for their CRM team.",
        buttonClass: 'brown-button',
        buttonTxt: 'CASE STUDY COMING SOON',
        imgContainer: 'brown-image-container',
        img: 'brown-image',
        imgURL: "https://mk0fivefiveagen2f17j.kinstacdn.com/wp-content/uploads/2020/10/starz-case-mobile-384x780.png",
        imgBg: 'brown-img-bg'
    },
    {
        id: 6,
        divID: 'blue',
        txtContainer: 'blue-txt-container',
        titleClass: 'blue-title',
        titleTxt: 'PIMCO',
        headlineClass: 'blue-headline',
        headlineTxt: '$1.92 Trillion Assets Under Management',
        paragraphClass: 'blue-paragraph',
        paragraphTxt: "FIVE is supporting PIMCO in their digital transformation by designing systems focused on their employees and customers.",
        buttonClass: 'blue-button',
        buttonTxt: 'CASE STUDY COMING SOON',
        imgContainer: 'blue-image-container',
        img: 'blue-image',
        imgURL: "https://mk0fivefiveagen2f17j.kinstacdn.com/wp-content/uploads/2020/10/pimco-case-desktop-1177x695.png",
        imgBg: 'blue-img-bg'
    },
    {
        id: 7,
        divID: 'green',
        txtContainer: 'green-txt-container',
        titleClass: 'green-title',
        titleTxt: 'MINT MOBILE',
        headlineClass: 'green-headline',
        headlineTxt: '400% Activations Increase',
        paragraphClass: 'green-paragraph',
        paragraphTxt: "With its gamified experiance and easy to use features, the Mint Mobile App saw a 400% increase in customer activations upsells and a 50% increase in user retention.",
        buttonClass: 'green-button',
        buttonTxt: 'CASE STUDY COMING SOON',
        imgContainer: 'green-image-container',
        img: 'green-image',
        imgURL: "https://mk0fivefiveagen2f17j.kinstacdn.com/wp-content/uploads/2020/04/mint-mobile-case-mobile-384x780.png",
        imgBg: 'green-img-bg'
    },
    {
        id: 8,
        divID: 'pink',
        txtContainer: 'pink-txt-container',
        titleClass: 'pink-title',
        titleTxt: 'NANIT',
        headlineClass: 'pink-headline',
        headlineTxt: '6 months to MVP',
        paragraphClass: 'pink-paragraph',
        paragraphTxt: "Nanit is the most sophisticated baby monitor on the market. Computer vision and machine learning help parents better understand their baby's sleep.",
        buttonClass: '',
        buttonTxt: '',
        imgContainer: 'pink-image-container',
        img: 'pink-image',
        imgURL: "https://mk0fivefiveagen2f17j.kinstacdn.com/wp-content/uploads/2020/04/nanit-case-mobile-384x780.png",
        imgBg: 'pink-img-bg'
    },
    {
        id: 9,
        divID: 'aqua',
        txtContainer: 'aqua-txt-container',
        titleClass: 'aqua-title',
        titleTxt: 'MOONLITE',
        headlineClass: 'aqua-headline',
        headlineTxt: '32% Weekly Active Users',
        paragraphClass: 'aqua-paragraph',
        paragraphTxt: "Acquisition cost -70%; Bounce rate -30%; Add to cart rate +80%; Conversion rate +90%; Average order value +20% and +50% customer lifetime value",
        buttonClass: '',
        buttonTxt: '',
        imgContainer: 'aqua-image-container',
        img: 'aqua-image',
        imgURL: 'https://mk0fivefiveagen2f17j.kinstacdn.com/wp-content/uploads/2020/04/moonlite-case-mobile-384x780.png'
    }
]

export default SectionList